# Generated by Django 4.1.4 on 2022-12-14 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyrrecy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_in', models.CharField(help_text='Валюта которую хотите поменять', max_length=3, verbose_name='CyrrencyInput')),
                ('currency_out', models.CharField(help_text='Валюта которую хотите получить', max_length=3, verbose_name='CyrrencyOutput')),
                ('currency_in_ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
